#!/usr/bin/env python3
"""Setup script for VulkanForge package."""

import os
import sys
import subprocess
import shutil
from pathlib import Path
from setuptools import setup, Extension, find_packages
from setuptools.command.build_ext import build_ext
from setuptools.command.build_py import build_py
from setuptools.command.develop import develop
from setuptools.command.install import install

# Read the README file
this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text() if (this_directory / "README.md").exists() else ""

class ShaderCompiler:
    """Helper class to compile GLSL shaders to SPIR-V."""
    
    @staticmethod
    def find_glslc():
        """Find glslc compiler."""
        # Try system PATH
        if shutil.which('glslc'):
            return 'glslc'
        
        # Try VULKAN_SDK environment variable
        vulkan_sdk = os.environ.get('VULKAN_SDK')
        if vulkan_sdk:
            glslc_path = os.path.join(vulkan_sdk, 'bin', 'glslc')
            if sys.platform == 'win32':
                glslc_path += '.exe'
            if os.path.exists(glslc_path):
                return glslc_path
        
        return None
    
    @staticmethod
    def compile_shaders(shader_dir):
        """Compile all shaders in directory."""
        shader_dir = Path(shader_dir)
        glslc = ShaderCompiler.find_glslc()
        
        if not glslc:
            print("WARNING: glslc not found. Using pre-compiled shaders only.")
            return False
        
        print(f"Found glslc: {glslc}")
        
        # Shader stage mapping
        stage_map = {
            'vertex': 'vertex',
            'fragment': 'fragment',
            'vert': 'vertex',
            'frag': 'fragment',
        }
        
        compiled_count = 0
        for glsl_file in shader_dir.glob('*.glsl'):
            # Determine shader stage
            stem = glsl_file.stem
            stage = None
            for key, value in stage_map.items():
                if key in stem.lower():
                    stage = value
                    break
            
            if not stage:
                print(f"WARNING: Cannot determine stage for {glsl_file}")
                continue
            
            spv_file = glsl_file.with_suffix('.spv')
            
            # Skip if already up-to-date
            if spv_file.exists() and spv_file.stat().st_mtime > glsl_file.stat().st_mtime:
                print(f"Skipping {glsl_file.name} (up-to-date)")
                continue
            
            # Compile shader
            try:
                cmd = [glslc, f'-fshader-stage={stage}', str(glsl_file), '-o', str(spv_file)]
                subprocess.run(cmd, check=True, capture_output=True)
                print(f"Compiled: {glsl_file.name} -> {spv_file.name}")
                compiled_count += 1
            except subprocess.CalledProcessError as e:
                print(f"ERROR compiling {glsl_file}: {e.stderr.decode()}")
                continue
        
        print(f"Compiled {compiled_count} shaders")
        return True

class CompileShadersMixin:
    """Mixin to add shader compilation to setup commands."""
    
    def compile_shaders(self):
        """Compile all shaders and generate embedded fallbacks."""
        # Find shader directories
        shader_dirs = []
        
        # Python package shaders
        python_shaders = Path('python/vulkan_forge/shaders')
        if python_shaders.exists():
            shader_dirs.append(python_shaders)
        else:
            # Alternative location
            alt_shaders = Path('vulkan_forge/shaders')
            if alt_shaders.exists():
                shader_dirs.append(alt_shaders)
        
        # Compile shaders in each directory
        for shader_dir in shader_dirs:
            print(f"\nCompiling shaders in: {shader_dir}")
            ShaderCompiler.compile_shaders(shader_dir)
            
            # Generate embedded SPIR-V fallbacks
            self.generate_embedded_spirv(shader_dir)
    
    def generate_embedded_spirv(self, shader_dir):
        """Generate Python file with embedded SPIR-V data."""
        shader_dir = Path(shader_dir)
        output_file = shader_dir / 'embedded_spirv.py'

                
        spv_files = list(shader_dir.glob('*.spv'))
        if not spv_files:
            print(f"No .spv files found in {shader_dir}")
            return
        
        valid_files.append(spv_file)
            
        for spv_file in valid_files:
            with open(spv_file, 'rb') as spv:
                data = spv.read()
        
        print(f"Generating embedded SPIR-V: {output_file}")
        
        with open(output_file, 'w') as f:
            f.write('"""Auto-generated embedded SPIR-V shader data.\n')
            f.write('Generated by setup.py - DO NOT EDIT\n"""\n\n')
            f.write('from typing import Dict\n\n')
            f.write('# Embedded SPIR-V bytecode for each shader\n')
            f.write('EMBEDDED_SPIRV: Dict[str, bytes] = {\n')
        # Only include valid SPIR-V files
        valid_files = []
        for spv_file in sorted(spv_files):
             with open(spv_file, 'rb') as spv:
                data = spv.read()
                shader_name = spv_file.stem
                f.write(f'    "{shader_name}": (\n')
                f.write('def get_shader(name: str) -> Optional[bytes]:\n')
                f.write('    """Get embedded shader by name (without extension)."""\n')
                f.write('    return EMBEDDED_SPIRV.get(name)\n')
                f.write('\n')
                f.write('def has_shader(name: str) -> bool:\n')
                f.write('    """Check if shader exists in embedded data."""\n')
                f.write('    return name in EMBEDDED_SPIRV\n')
                f.write('\n')
                f.write("__all__ = ['get_shader', 'has_shader', 'EMBEDDED_SPIRV']\n")
                
                # Write bytes in readable chunks
                for i in range(0, len(data), 16):
                    chunk = data[i:i+16]
                    hex_bytes = ''.join(f'\\x{b:02x}' for b in chunk)
                    f.write(f'        b"{hex_bytes}"\n')
                
                f.write('    ),\n')
            
            f.write('}\n\n')
            f.write('def get_shader(name: str) -> bytes:\n')
            f.write('    """Get embedded shader bytecode by name."""\n')
            f.write('    return EMBEDDED_SPIRV.get(name, b"")\n')


class BuildPyCommand(build_py, CompileShadersMixin):
    """Custom build_py command that compiles shaders."""
    
    def run(self):
        self.compile_shaders()
        super().run()


class BuildExtCommand(build_ext, CompileShadersMixin):
    """Custom build_ext command that compiles shaders."""
    
    def run(self):
        self.compile_shaders()
        super().run()


class DevelopCommand(develop, CompileShadersMixin):
    """Custom develop command that compiles shaders."""
    
    def run(self):
        self.compile_shaders()
        super().run()


class InstallCommand(install, CompileShadersMixin):
    """Custom install command that compiles shaders."""
    
    def run(self):
        self.compile_shaders()
        super().run()


# Read version from __init__.py
def get_version():
    init_file = Path('python/vulkan_forge/__init__.py')
    if not init_file.exists():
        init_file = Path('vulkan_forge/__init__.py')
    
    with open(init_file, 'r') as f:
        for line in f:
            if line.startswith('__version__'):
                return line.split('=')[1].strip().strip('"\'')
    return '0.1.0'

setup(
    name="vulkan-forge",
    version="0.1.0",
    author="VulkanForge Team",
    author_email="",
    description="Multi-GPU renderer with automatic CPU fallback",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/vulkan-forge",
    packages=find_packages(where='python'),
    package_dir={'': 'python'},
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Multimedia :: Graphics :: 3D Rendering",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.7",
    package_data={
        'vulkan_forge': [
            'shaders/*.glsl',
            'shaders/*.spv',
            'shaders/*.vert',
            'shaders/*.frag',
            'shaders/embedded_spirv.py',
        ],
    },
    include_package_data=True,
    install_requires=[
        "numpy>=1.19.0",
        "pillow>=8.0.0",
    ],
    cmdclass={
        'build_py': BuildPyCommand,
        'build_ext': BuildExtCommand,
        'develop': DevelopCommand,
        'install': InstallCommand,
    },
    entry_points={
        'console_scripts': [
            'vf-compile-shaders=vulkan_forge.compile_shaders:main',
        ],
    },
    extras_require={
        "dev": [
            "pytest>=6.0",
            "black>=21.0",
            "flake8>=3.9",
        ],
        "vulkan": [
            "vulkan>=1.2.0",
        ],
    },
)