#!/usr/bin/env python3
"""Setup script for Vulkan-Forge package."""

import os
import sys
import subprocess
import shutil
from pathlib import Path
from setuptools import setup, Extension, find_packages
from setuptools.command.build_ext import build_ext
from setuptools.command.build_py import build_py
from setuptools.command.develop import develop
from setuptools.command.install import install

# Read the README file
this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text() if (this_directory / "README.md").exists() else ""

class ShaderCompiler:
    """Helper class to compile GLSL shaders to SPIR-V."""
    
    @staticmethod
    def find_glslc():
        """Find glslc compiler."""
        # Try system PATH
        if shutil.which('glslc'):
            return 'glslc'
        
        # Try VULKAN_SDK environment variable
        vulkan_sdk = os.environ.get('VULKAN_SDK')
        if vulkan_sdk:
            glslc_path = os.path.join(vulkan_sdk, 'bin', 'glslc')
            if sys.platform == 'win32':
                glslc_path += '.exe'
            if os.path.exists(glslc_path):
                return glslc_path
        
        return None
    
    @staticmethod
    def compile_shaders(shader_dir):
        """Compile all shaders in directory."""
        shader_dir = Path(shader_dir)
        glslc = ShaderCompiler.find_glslc()
        
        if not glslc:
            print("WARNING: glslc not found. Using pre-compiled shaders only.")
            return False
        
        print(f"Found glslc: {glslc}")
        
        # Shader stage mapping
        stage_map = {
            'vert': 'vertex',
            'frag': 'fragment',
            'comp': 'compute',
            'geom': 'geometry',
            'tesc': 'tesscontrol',
            'tese': 'tesseval',
        }
        
        compiled_count = 0
        shader_files = list(shader_dir.glob('*.vert')) + list(shader_dir.glob('*.frag')) + \
                      list(shader_dir.glob('*.comp')) + list(shader_dir.glob('*.geom'))
        
        for glsl_file in shader_files:
            # Determine shader stage from extension
            stage = stage_map.get(glsl_file.suffix[1:])  # Remove the '.'
            
            if not stage:
                print(f"WARNING: Cannot determine stage for {glsl_file}")
                continue
            
            spv_file = glsl_file.with_suffix('.spv')
            
            # Skip if already up-to-date
            if spv_file.exists() and spv_file.stat().st_mtime > glsl_file.stat().st_mtime:
                print(f"Skipping {glsl_file.name} (up-to-date)")
                continue
            
            # Compile shader
            try:
                cmd = [glslc, f'-fshader-stage={stage}', str(glsl_file), '-o', str(spv_file)]
                subprocess.run(cmd, check=True, capture_output=True)
                print(f"Compiled: {glsl_file.name} -> {spv_file.name}")
                compiled_count += 1
            except subprocess.CalledProcessError as e:
                print(f"ERROR compiling {glsl_file}: {e.stderr.decode()}")
                continue
        
        print(f"Compiled {compiled_count} shaders")
        return True

class CompileShadersMixin:
    """Mixin to add shader compilation to setup commands."""
    
    def compile_shaders(self):
        """Compile all shaders and generate embedded fallbacks."""
        # Find shader directories
        shader_dirs = []
        
        # Python package shaders
        python_shaders = Path('python/vulkan_forge/shaders')
        if python_shaders.exists():
            shader_dirs.append(python_shaders)
        else:
            # Alternative location
            alt_shaders = Path('vulkan_forge/shaders')
            if alt_shaders.exists():
                shader_dirs.append(alt_shaders)
        
        # C++ shaders
        cpp_shaders = Path('cpp/shaders')
        if cpp_shaders.exists():
            shader_dirs.append(cpp_shaders)
        
        # Compile shaders in each directory
        for shader_dir in shader_dirs:
            print(f"\nCompiling shaders in: {shader_dir}")
            ShaderCompiler.compile_shaders(shader_dir)
            
            # Generate embedded SPIR-V fallbacks
            self.generate_embedded_spirv(shader_dir)
    
    def generate_embedded_spirv(self, shader_dir):
        """Generate Python file with embedded SPIR-V data."""
        shader_dir = Path(shader_dir)
        output_file = shader_dir / 'embedded_spirv.py'
        
        spv_files = list(shader_dir.glob('*.spv'))
        if not spv_files:
            print(f"No .spv files found in {shader_dir}")
            return
        
        print(f"Generating embedded SPIR-V: {output_file}")
        
        with open(output_file, 'w') as f:
            f.write('"""Auto-generated embedded SPIR-V shader data.\n')
            f.write('Generated by setup.py - DO NOT EDIT\n"""\n\n')
            f.write('from typing import Dict, Optional\n\n')
            f.write('# Embedded SPIR-V bytecode for each shader\n')
            f.write('EMBEDDED_SPIRV: Dict[str, bytes] = {\n')
            
            # Only include valid SPIR-V files
            valid_files = []
            for spv_file in sorted(spv_files):
                try:
                    with open(spv_file, 'rb') as spv:
                        data = spv.read()
                        
                    # Basic SPIR-V validation (check magic number)
                    if len(data) >= 4:
                        magic = int.from_bytes(data[:4], byteorder='little')
                        if magic == 0x07230203:  # SPIR-V magic number
                            valid_files.append((spv_file, data))
                        else:
                            print(f"WARNING: {spv_file} is not a valid SPIR-V file")
                    else:
                        print(f"WARNING: {spv_file} is too small to be valid SPIR-V")
                except Exception as e:
                    print(f"WARNING: Failed to read {spv_file}: {e}")
            
            for spv_file, data in valid_files:
                shader_name = spv_file.stem
                f.write(f'    "{shader_name}": (\n')
                
                # Write bytes in readable chunks
                for i in range(0, len(data), 16):
                    chunk = data[i:i+16]
                    hex_bytes = ''.join(f'\\x{b:02x}' for b in chunk)
                    f.write(f'        b"{hex_bytes}"\n')
                
                f.write('    ),\n')
            
            f.write('}\n\n')
            f.write('def get_shader(name: str) -> Optional[bytes]:\n')
            f.write('    """Get embedded shader by name (without extension)."""\n')
            f.write('    return EMBEDDED_SPIRV.get(name)\n')
            f.write('\n')
            f.write('def has_shader(name: str) -> bool:\n')
            f.write('    """Check if shader exists in embedded data."""\n')
            f.write('    return name in EMBEDDED_SPIRV\n')
            f.write('\n')
            f.write('def list_shaders() -> list:\n')
            f.write('    """List all available shader names."""\n')
            f.write('    return list(EMBEDDED_SPIRV.keys())\n')
            f.write('\n')
            f.write("__all__ = ['get_shader', 'has_shader', 'list_shaders', 'EMBEDDED_SPIRV']\n")


class BuildPyCommand(build_py, CompileShadersMixin):
    """Custom build_py command that compiles shaders."""
    
    def run(self):
        self.compile_shaders()
        super().run()


class BuildExtCommand(build_ext, CompileShadersMixin):
    """Custom build_ext command that compiles shaders."""
    
    def run(self):
        self.compile_shaders()
        super().run()


class DevelopCommand(develop, CompileShadersMixin):
    """Custom develop command that compiles shaders."""
    
    def run(self):
        self.compile_shaders()
        super().run()


class InstallCommand(install, CompileShadersMixin):
    """Custom install command that compiles shaders."""
    
    def run(self):
        self.compile_shaders()
        super().run()


# Read version from __init__.py
def get_version():
    init_file = Path('python/vulkan_forge/__init__.py')
    if not init_file.exists():
        init_file = Path('vulkan_forge/__init__.py')
    
    if init_file.exists():
        with open(init_file, 'r') as f:
            for line in f:
                if line.startswith('__version__'):
                    return line.split('=')[1].strip().strip('"\'')
    return '0.1.0'

setup(
    name="vulkan-forge",
    version=get_version(),
    author="VulkanForge Team",
    author_email="",
    description="High-performance mesh rendering with Vulkan - OBJ loader to GPU at 1000+ FPS",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/vulkan-forge",
    packages=find_packages(where='python'),
    package_dir={'': 'python'},
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Multimedia :: Graphics :: 3D Rendering",
        "Topic :: Scientific/Engineering :: Visualization",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: C++",
        "Operating System :: Microsoft :: Windows",
        "Operating System :: POSIX :: Linux",
        "Operating System :: MacOS",
    ],
    keywords="vulkan graphics rendering mesh obj 3d gpu",
    python_requires=">=3.8",
    package_data={
        'vulkan_forge': [
            'shaders/*.glsl',
            'shaders/*.spv',
            'shaders/*.vert',
            'shaders/*.frag',
            'shaders/*.comp',
            'shaders/embedded_spirv.py',
        ],
        'vulkan_forge.loaders': ['*.py'],
    },
    include_package_data=True,
    install_requires=[
        "numpy>=1.19.0,<2.1.0",  # Pin numpy for Python 3.9 compatibility
        "pillow>=8.0.0",
    ],
    cmdclass={
        'build_py': BuildPyCommand,
        'build_ext': BuildExtCommand,
        'develop': DevelopCommand,
        'install': InstallCommand,
    },
    entry_points={
        'console_scripts': [
            'vf-compile-shaders=vulkan_forge.compile_shaders:main',
            'vf-mesh-viewer=vulkan_forge.tools.mesh_viewer:main',
            'vf-benchmark=vulkan_forge.tools.benchmark:main',
        ],
    },
    extras_require={
        "dev": [
            "pytest>=6.0",
            "black>=21.0",
            "flake8>=3.9",
            "mypy>=0.910",
        ],
        "vulkan": [
            "vulkan>=1.2.0",
        ],
        "tools": [
            "click>=7.0",
            "tqdm>=4.0",
        ],
        "examples": [
            "matplotlib>=3.0",
            "requests>=2.25",
        ],
    },
    zip_safe=False,  # Required for proper C++ extension loading
    
    # Build configuration for C++ extension
    ext_modules=[],  # Will be built by CMake via pybind11
    
    # Project URLs
    project_urls={
        "Bug Reports": "https://github.com/yourusername/vulkan-forge/issues",
        "Source": "https://github.com/yourusername/vulkan-forge",
        "Documentation": "https://vulkan-forge.readthedocs.io/",
    },
)