use serde::Deserialize;

use super::defaults::{
    default_depth_bias, default_drape_offset, default_fov, default_intensity, default_line_width,
    default_max_points, default_oit_mode, default_opacity, default_phi, default_point_size,
    default_primitive, default_radius, default_sun_azimuth, default_sun_elevation,
    default_sun_intensity, default_theta, default_true, default_up,
};
use super::payloads::{
    IpcDenoiseConfig, IpcDofConfig, IpcHeightAoConfig, IpcLensEffectsConfig,
    IpcMaterialLayerConfig, IpcMotionBlurConfig, IpcSceneReviewState, IpcSkyConfig,
    IpcSunVisConfig, IpcTerrainScatterBatch, IpcTonemapConfig, IpcVectorOverlayConfig,
    IpcVolumetricsConfig,
};

#[rustfmt::skip]
#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "cmd", rename_all = "snake_case")]
pub enum IpcRequest {
    GetStats,
    LoadObj { path: String },
    LoadGltf { path: String },
    SetTransform { #[serde(default)] translation: Option<[f64; 3]>, #[serde(default)] rotation_quat: Option<[f32; 4]>, #[serde(default)] scale: Option<[f32; 3]> },
    CamLookat { eye: [f64; 3], target: [f64; 3], #[serde(default = "default_up")] up: [f32; 3] },
    SetFov { deg: f32 },
    LitSun { azimuth_deg: f32, elevation_deg: f32 },
    SetObservation { year: i32, month: u8, day: u8, hour: u8, minute: u8, second: f64, latitude_deg: f64, longitude_deg: f64, #[serde(default)] height_m: f64 },
    LitIbl { path: String, #[serde(default = "default_intensity")] intensity: f32 },
    SetZScale { value: f32 },
    Snapshot { path: String, #[serde(default)] width: Option<u32>, #[serde(default)] height: Option<u32> },
    Close,
    SaveBundle { path: String, #[serde(default)] name: Option<String> },
    LoadBundle { path: String },
    LoadTerrain { path: String },
    SetTerrainCamera {
        #[serde(default = "default_phi")] phi_deg: f32,
        #[serde(default = "default_theta")] theta_deg: f32,
        #[serde(default = "default_radius")] radius: f32,
        #[serde(default = "default_fov")] fov_deg: f32,
        #[serde(default)] target: Option<[f64; 3]>,
    },
    SetTerrainSun { #[serde(default = "default_sun_azimuth")] azimuth_deg: f32, #[serde(default = "default_sun_elevation")] elevation_deg: f32, #[serde(default = "default_sun_intensity")] intensity: f32, #[serde(default)] source: Option<String> },
    SetTerrain {
        #[serde(default)] phi: Option<f32>, #[serde(default)] theta: Option<f32>, #[serde(default)] radius: Option<f32>,
        #[serde(default)] fov: Option<f32>, #[serde(default)] sun_azimuth: Option<f32>, #[serde(default)] sun_elevation: Option<f32>,
        #[serde(default)] sun_intensity: Option<f32>, #[serde(default)] ambient: Option<f32>, #[serde(default)] zscale: Option<f32>,
        #[serde(default)] shadow: Option<f32>, #[serde(default)] background: Option<[f32; 3]>, #[serde(default)] water_level: Option<f32>,
        #[serde(default)] water_color: Option<[f32; 3]>,
        #[serde(default)] target: Option<[f64; 3]>,
    },
    SetTerrainScatter { #[serde(default)] batches: Vec<IpcTerrainScatterBatch> },
    ClearTerrainScatter,
    GetTerrainParams,
    GetTerrainVolumetricsReport,
    SetTerrainPbr {
        #[serde(default)] enabled: Option<bool>, #[serde(default)] hdr_path: Option<String>, #[serde(default)] ibl_intensity: Option<f32>,
        #[serde(default, alias = "hdr_rotate")] hdr_rotate_deg: Option<f32>,
        #[serde(default)] shadow_technique: Option<String>, #[serde(default)] shadow_map_res: Option<u32>, #[serde(default)] exposure: Option<f32>,
        #[serde(default)] msaa: Option<u32>, #[serde(default)] normal_strength: Option<f32>, #[serde(default)] height_ao: Option<IpcHeightAoConfig>,
        #[serde(default)] sun_visibility: Option<IpcSunVisConfig>, #[serde(default)] materials: Option<IpcMaterialLayerConfig>,
        #[serde(default)] vector_overlay: Option<IpcVectorOverlayConfig>, #[serde(default)] tonemap: Option<IpcTonemapConfig>,
        #[serde(default)] dof: Option<IpcDofConfig>, #[serde(default)] motion_blur: Option<IpcMotionBlurConfig>,
        #[serde(default)] lens_effects: Option<IpcLensEffectsConfig>, #[serde(default)] denoise: Option<IpcDenoiseConfig>,
        #[serde(default)] volumetrics: Option<IpcVolumetricsConfig>, #[serde(default)] sky: Option<IpcSkyConfig>, #[serde(default)] debug_mode: Option<u32>,
    },
    LoadOverlay { name: String, path: String, #[serde(default)] extent: Option<[f32; 4]>, #[serde(default)] opacity: Option<f32>, #[serde(default)] z_order: Option<i32> },
    RemoveOverlay { id: u32 },
    SetOverlayVisible { id: u32, visible: bool },
    SetOverlayOpacity { id: u32, opacity: f32 },
    SetGlobalOverlayOpacity { opacity: f32 },
    SetOverlaysEnabled { enabled: bool },
    SetOverlaySolid { solid: bool },
    SetOverlayPreserveColors { preserve_colors: bool },
    ListOverlays,
    AddVectorOverlay {
        #[serde(default)] id: Option<u32>, name: String, vertices: Vec<crate::viewer::viewer_enums::ViewerVectorVertex>, indices: Vec<u32>, #[serde(default = "default_primitive")] primitive: String,
        #[serde(default)] drape: bool, #[serde(default = "default_drape_offset")] drape_offset: f32, #[serde(default = "default_opacity")] opacity: f32,
        #[serde(default = "default_depth_bias")] depth_bias: f32, #[serde(default = "default_line_width")] line_width: f32, #[serde(default = "default_point_size")] point_size: f32,
        #[serde(default)] z_order: i32,
    },
    RemoveVectorOverlay { id: u32 },
    SetVectorOverlayVisible { id: u32, visible: bool },
    SetVectorOverlayOpacity { id: u32, opacity: f32 },
    ListVectorOverlays,
    SetVectorOverlaysEnabled { enabled: bool },
    SetGlobalVectorOverlayOpacity { opacity: f32 },
    LoadPointCloud { path: String, #[serde(default = "default_point_size")] point_size: f32, #[serde(default = "default_max_points")] max_points: u64, #[serde(default)] color_mode: Option<String> },
    ClearPointCloud,
    SetPointCloudParams {
        #[serde(default)] point_size: Option<f32>,
        #[serde(default)] visible: Option<bool>,
        #[serde(default)] color_mode: Option<String>,
        #[serde(default)] phi: Option<f32>,
        #[serde(default)] theta: Option<f32>,
        #[serde(default)] radius: Option<f32>,
    },
    AddLabel {
        #[serde(default)] id: Option<u64>, text: String, world_pos: [f64; 3], #[serde(default)] size: Option<f32>, #[serde(default)] color: Option<[f32; 4]>, #[serde(default)] halo_color: Option<[f32; 4]>,
        #[serde(default)] halo_width: Option<f32>, #[serde(default)] priority: Option<i32>, #[serde(default)] min_zoom: Option<f32>, #[serde(default)] max_zoom: Option<f32>,
        #[serde(default)] offset: Option<[f32; 2]>, #[serde(default)] rotation: Option<f32>, #[serde(default)] underline: Option<bool>, #[serde(default)] small_caps: Option<bool>,
        #[serde(default)] leader: Option<bool>, #[serde(default)] horizon_fade_angle: Option<f32>,
    },
    AddLineLabel {
        #[serde(default)] id: Option<u64>, text: String, polyline: Vec<[f64; 3]>, #[serde(default)] size: Option<f32>, #[serde(default)] color: Option<[f32; 4]>, #[serde(default)] halo_color: Option<[f32; 4]>,
        #[serde(default)] halo_width: Option<f32>, #[serde(default)] priority: Option<i32>, #[serde(default)] placement: Option<String>, #[serde(default)] repeat_distance: Option<f32>,
        #[serde(default)] min_zoom: Option<f32>, #[serde(default)] max_zoom: Option<f32>,
    },
    RemoveLabel { id: u64 },
    ClearLabels,
    SetLabelsEnabled { enabled: bool },
    LoadLabelAtlas { atlas_png_path: String, metrics_json_path: String },
    SetLabelZoom { zoom: f32 },
    SetMaxVisibleLabels { max: usize },
    AddCurvedLabel {
        #[serde(default)] id: Option<u64>, text: String, polyline: Vec<[f64; 3]>, #[serde(default)] size: Option<f32>, #[serde(default)] color: Option<[f32; 4]>, #[serde(default)] halo_color: Option<[f32; 4]>,
        #[serde(default)] halo_width: Option<f32>, #[serde(default)] priority: Option<i32>, #[serde(default)] tracking: Option<f32>, #[serde(default = "default_true")] center_on_path: bool,
    },
    AddCallout {
        #[serde(default)] id: Option<u64>, text: String, anchor: [f64; 3], #[serde(default)] offset: Option<[f32; 2]>, #[serde(default)] background_color: Option<[f32; 4]>, #[serde(default)] border_color: Option<[f32; 4]>,
        #[serde(default)] border_width: Option<f32>, #[serde(default)] corner_radius: Option<f32>, #[serde(default)] padding: Option<f32>, #[serde(default)] text_size: Option<f32>,
        #[serde(default)] text_color: Option<[f32; 4]>,
    },
    RemoveCallout { id: u64 },
    SetLabelTypography { #[serde(default)] tracking: Option<f32>, #[serde(default)] kerning: Option<bool>, #[serde(default)] line_height: Option<f32>, #[serde(default)] word_spacing: Option<f32> },
    SetDeclutterAlgorithm { algorithm: String, #[serde(default)] seed: Option<u64>, #[serde(default)] max_iterations: Option<usize> },
    PickAt { x: u32, y: u32, #[serde(default)] shift: bool, #[serde(default)] ctrl: bool },
    PollPickEvents,
    UpdateLabels,
    SetLassoMode { enabled: bool },
    GetLassoState,
    ClearSelection,
    SetSceneReviewState { state: IpcSceneReviewState },
    ListSceneVariants,
    ListReviewLayers,
    GetActiveSceneVariant,
    ApplySceneVariant { variant_id: String },
    SetReviewLayerVisible { layer_id: String, visible: bool },
    SetOitEnabled { enabled: bool, #[serde(default = "default_oit_mode")] mode: String },
    GetOitMode,
    SetTaaEnabled { enabled: bool },
    GetTaaStatus,
    SetTaaParams { #[serde(default)] history_weight: Option<f32>, #[serde(default)] jitter_scale: Option<f32>, #[serde(default)] enable_jitter: Option<bool> },
    PollPendingBundleSave,
    PollPendingBundleLoad,
}
